# Generated by Django 4.2.9 on 2024-12-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Инструменты', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
